import { ExerciseId } from "@/constants/exercises";

export const AI_COACH_API_URL =
  "https://unfull-hyperflexibly-marylynn.ngrok-free.dev/v1/chat/completions";
export const AI_COACH_MODEL = "local-llama";

export const REP_MIN = 1;
export const REP_MAX = 99;
export const ROUND_MIN = 1;
export const ROUND_MAX = 10;
export const HISTORY_WINDOW = 8;
export const MAX_TOKENS = 200;
export const TEMPERATURE = 0.1;

export const ALLOWED_EXERCISES: ExerciseId[] = [
  ExerciseId.SQUATS,
  ExerciseId.PUSHUPS,
  ExerciseId.HAMMER_CURLS,
  ExerciseId.LATERAL_RAISES,
];

export const LEVEL_REGEX =
  /(principiante|intermedio|avanzado|beginner|intermediate|advanced)/i;

export const AGE_REGEX =
  /(\b\d{1,2}\s*(años?|year|years?)\b|\bedad\s*(?:es\s*)?\d{1,2}\b|\btengo\s+\d{1,2}(?:\s*(?:años?|year|years?)\b)?(?:\s+de\s+edad)?(?=\s*(?:$|[,.!?;]|y\b|con\b)))/i;
export const FREQUENCY_REGEX =
  /(\b\d{1,2}\s*(veces|times)\s*(por\s+)?(semana|week|weeks)\b|\b(entreno|entrenas|train)\s*\d{1,2}\b)/i;

export const AFFIRMATIVE_REGEX =
  /^(si|sí|sii|vale|ok|okay|dale|claro|listo|va|de una|yes|yep|sure|correcto|entendido)\b/i;

export const TOPIC_KEYWORDS = [
  "coach",
  "entrenador",
  "plan",
  "rutina",
  "routine",
  "workout",
  "training",
  "reps",
  "sets",
  "series",
  "rounds",
  "intensity",
  "strength",
  "hypertrophy",
  "mobility",
  "cardio",
  "warmup",
  "cooldown",
  "programa",
  "fuerza",
  "resistencia",
  "frecuencia",
  "duración",
  "objetivo",
  "equipment",
  "mancuerna",
  "dumbbell",
  "peso",
  "load",
  "nivel",
  "beginner",
  "intermediate",
  "advanced",
  "principiante",
  "intermedio",
  "avanzado",
  "flexiones",
  "pushups",
  "sentadillas",
  "squats",
  "hammer curls",
  "curl de martillo",
  "elevaciones",
  "laterales",
  "lateral",
  "raises",
  "pesas",
  "weights",
  "bandas",
  "bands",
  "cuerda",
  "rope",
  "kettlebell",
  "kettlebell",
  "barra",
  "barbell",
  "press",
  "brazos",
  "arms",
  "piernas",
  "legs",
  "espalda",
  "back",
  "pecho",
  "chest",
  "hombros",
  "shoulders",
  "abdominales",
  "abs",
  "cardio",
  "strength",
  "fuerza",
  "resistencia",
  "endurance",
  "flexibilidad",
  "flexibility",
  "movilidad",
  "mobility",
  //lista ampliada con más sinónimos y términos relacionados a la medicina deportiva
  "salud",
  "health",
  "lesión",
  "injury",
  "recuperación",
  "recovery",
  "bienestar",
  "wellness",
  "nutrición",
  "nutrition",
  "dieta",
  "diet",
  "suplementos",
  "supplements",
  "hidratación",
  "hydration",
  "descanso",
  "rest",
  "sueño",
  "sleep",
  "estrés",
  "stress",
  "mental",
  "mental",
  "motivación",
  "motivation",
  "objetivos",
  "goals",
  "progreso",
  "progress",
  "repeticiones",
  "repetitions",
  "año",
  "edad",
  "semanal",
  "nivel",
  "veces",
  "frecuencia",
  "train",
  "entrenas",
  "week",
  "weekly",
  "times",
  "age",
  "rondas",
  "rounds",
  "ronda",
  "round",
  //dame terminos de una palabra relacionados con ejercicio fisico y entrenamiento en español e ingles
  "salud",
  "health",
  "fuerza",
  "strength",
  "resistencia",
  "endurance",
  "flexibilidad",
  "flexibility",
  "movilidad",
  "mobility",
  "cardio",
  "pesas",
  "weights",
  "bandas",
  "bands",
  "cuerda",
  "rope",
  "barra",
  "barbell",
  "press",
  "brazos",
  "arms",
  "piernas",
  "legs",
  "espalda",
  "back",
  "pecho",
  "chest",
  "hombros",
  "shoulders",
  "abdominales",
  "abs",
  "hola",
  "hello",
  "adiós",
  "goodbye",
  "gracias",
  "thanks",
  "por favor",
  "please",
] as const;
